twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        qr_public_base_url: '%qr.public_base_url%'

when@test:
    twig:
        strict_variables: true
