controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Gestion des langues
app_switch_language:
    path: /language/{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'forum_index'