# This file is the entry point to configure your own services.

parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\BadWordFilter:
        arguments:
            $badWordsFile: '%kernel.project_dir%/config/badwords.json'

    App\Command\BadWordsCommand:
        arguments:
            $badWordsFile: '%kernel.project_dir%/config/badwords.json'